      parameter (NUMSTS=30)
c
c ... integer variables:
c
      COMMON/MDI/NRUN,NRP,NSM,NRAM,NSPM,IG,NRU,
     +   NTX,NTCX,NTXO,NTT,NTP,NTR,INIT,NTCM,NSCM,NTU,
     +      ISOLVP,NSOLUT,NTC,NTCC,NTF,NTID,NTN,NTNB,NSNB,NDFMIN,
     +      NSTLIM,NRC,NTRX,NPSCAL,IMIN,MAXCYC,NCYC,NTMIN,
     +      IREST,JFASTW,IWTNM,IOWTNM,IHWTNM(2),IBGWAT,IENWAT,IORWAT,
     +      IWATPR,NSOLW
c
c ... floats:
c
      COMMON/MDR/T,DT,TEMP0,TAUTP,TAUTS,PRES0,COMP,TAUP,TEMP,TEMPI,
     +      HEAT,TOL,DTEMP,TAUR,DX0,DXM,DRMS,TIMLIM,TIMTOT,TIMDEL,
     +      TIMRUN,TIMSTS(NUMSTS),TAUV,TAUV0,VZERO,VLIMIT,RBTARG(8),
     +      tmass,tmassinv
